### ISSUE TITLE
Promise from `Guild.createRole` does not fail when maximum role limit is reached.

### ISSUE THREAD

**Issue by Miroware8** [hydrabolt/discord.js#1787] opened 2017-08-17 02:14 UTC
**Please describe the problem you are having in as much detail as possible:**
![image](https://user-images.githubusercontent.com/14056899/29393131-01cb1e4c-82d0-11e7-9dc9-f338c5a4f6ec.png)
In that image, I've placed two red marks next to some code. In most cases, only the first marked line would run. In a case where Discord's maximum role limit is reached, you'd expect that the second marked line would run after the promise fails. Instead, when the maximum role limit is reached and `Guild.createRole` is called, neither line runs and nothing happens. The promise doesn't fail and no error or warning is displayed in the console.

**Further details:**

- discord.js version: 11.1.0
- node.js version: 7.8.0
- Operating system: Ubuntu 16.04.3 LTS
- Priority this issue should have – please be realistic and elaborate if possible:
This issue does not need high priority, as I can just tell members myself that we've hit the role limit instead of having the bot do it automatically.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by ShayBox** [comment] 2017-08-21 02:36
Same with createChannel

**Comment by devsnek** [comment] 2017-08-21 02:41
@ShayBox @Miroware8 please confirm the master hashes you tested this bug with

**Comment by Miroware8** [comment] 2017-08-22 18:46
@devsnek How?

**Comment by CyberiumShadow** [comment] 2017-08-28 02:18
@Miroware8 check your package-lock.json

**Comment by Miroware8** [comment] 2017-08-29 22:11
@CyberiumShadow What am I looking for?

**Comment by CyberiumShadow** [comment] 2017-08-30 02:18
@Miroware8 A line that looks like this 
![image](https://user-images.githubusercontent.com/4259904/29852410-4c9f03ea-8d7d-11e7-8708-b26d026794f6.png)

**Comment by devsnek** [comment] 2017-08-30 03:40
or like `npm ls discord.js`

**Comment by robflop** [comment] 2017-09-03 04:08
I've confirmed that both errors are emitted on commit hash c4df2502 of master.

Channel limit: http://i.imgur.com/WIhLjtu.png

Role limit: http://i.imgur.com/dLpr9gz.png

**Comment by Miroware8** [comment] 2017-09-04 18:16
@CyberiumShadow I don't have a line like that. All three occurrences of "`discord.js`" are in this screenshot.
![image](https://user-images.githubusercontent.com/14056899/30035786-a91663aa-917b-11e7-8e02-48c46483bd6f.png)

**Comment by robflop** [comment] 2017-09-04 19:46
@Miroware8 Gus was asking about the master branch commit you tested this on -- but seeing as you're on version 11.1, I assume you didn't. Also see my comment above, the issue is fixed on the master branch.

**Comment by iCrawl** [comment] 2017-09-05 17:53
^

**Closed by iCrawl** 2017-09-05 17:53 UTC
Labels: p: low, t: REST, type: bug
