### ISSUE TITLE
addMemberToRole and removeMemberFromRole

### ISSUE THREAD

**Issue by Juceztp** [hydrabolt/discord.js#476] opened 2016-07-25 18:46 UTC
Hi, i just want to assign and remove a role to the same user. Sometimes the bot assigns Role1 but does not remove the Role2 or remove the Role2 but does not assign Role1. No error in the console logs.

My code

```
//ASSIGN ROLE
role = message.server.roles.get("name", 'Role1');
mybot.addMemberToRole(user, role, function (err) {
    if (err) {
        console.log(err);
    }
})

//REMOVE ROLE
role = message.server.roles.get("name", 'Role2');
mybot.removeMemberFromRole(user, role, function (err) {
    if (err) {
        console.log(err);
    }
});
```

**Comment by GexoXYZ** [comment] 2016-07-25 19:38
Nest it in the callback

**Comment by abalabahaha** [comment] 2016-07-26 00:41
Essentially a duplicate of #472

**Closed by abalabahaha** 2016-07-26 00:41 UTC
Labels: question
