### ISSUE TITLE
ffmpeg proccess

### ISSUE THREAD

**Issue by nevermnd** [hydrabolt/discord.js#774] opened 2016-10-06 19:44 UTC
The bot is not killing ffmpeg's proccess properly, causing each consecutive call to `playStream` to spawn a new proccess at the top of the previous one.
This only happens when the `StreamDispatcher` "end" event is triggered manually. If the event is triggered by the stream reaching it's end, the proccess is ended as intended.

![ffmpeg](https://cloud.githubusercontent.com/assets/5993725/19167841/d4b25b98-8be3-11e6-9233-57e0e1139087.png)

**Comment by macdja38** [comment] 2016-10-06 20:36
it's possible this is caused by the library attempting to kill the FFMPEG during a networking operation causing it to become stuck in a ghost state.

**Comment by hydrabolt** [comment] 2016-10-26 08:50
This should be fixed in indev, but why are you manually triggering end?

**Closed** 2016-10-26 13:35 UTC
Labels: potential bug, voice
