### ISSUE TITLE
Issue with voice connections

### ISSUE THREAD

**Issue by OkitaSougoo** [hydrabolt/discord.js#1595] opened 2017-06-14 23:33 UTC
**Please describe the problem you are having in as much detail as possible:**
In the server setting, my bot has permission to `connect`. However, I set up a specific voice channel which disabled everyone's permission to `connect` (which should overwrite the server permission). But when I log `voiceChannel.joinable`, it is returning `true`, so my bot still tries to join, and it stuck at VoiceStatus 2(AUTHENTICATING). After about 15 seconds, I get the following unhandled error and the program crashed:
```js
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/Users/user/Documents/NodeJS/MusicBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:257:26)
    at connectTimeout.client.setTimeout (/Users/user/Documents/NodeJS/MusicBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:278:18)
    at Timeout.setTimeout (/Users/user/Documents/NodeJS/MusicBot/node_modules/discord.js/src/client/Client.js:446:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! musicbot@1.0.0 start: `node --optimize_for_size src/main.js`
npm ERR! Exit status 1
```

**Include a reproducible code sample here, if possible:**
```js
onst Discord = require('discord.js');
const client = new Discord.Client();

client.login('token here');

client.on('message', message => {
  // Voice only works in guilds, if the message does not come from a guild,
  // we ignore it
  if (!message.guild) return;

  if (message.content === '/join') {
    // Only try to join the sender's voice channel if they are in one themselves
    if (message.member.voiceChannel) {
      // check if there is already a voice connection
      if (message.member.voiceChannel.connection) {
        console.log('conn status: ' + message.member.voiceChannel.connection.status);
      }
      console.log('is joinable: ' + message.member.voiceChannel.joinable);
      if (message.member.voiceChannel.joinable) {
        message.member.voiceChannel.join()
          .then(connection => { // Connection is an instance of VoiceConnection
            message.reply('I have successfully connected to the channel!');
          })
          .catch(console.error);
      }
    } else {
      message.reply('You need to join a voice channel first!');
    }
  }
});
```

**Further details:**

- discord.js version: Master
- node.js version: 8.0.0
- Operating system: Windows 10
- Priority this issue should have – high

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by aemino** [comment] 2017-06-14 23:35
Joinable is a property, not a function.

**Comment by OkitaSougoo** [comment] 2017-06-14 23:38
@aemino oops sorry typo in my part. But i my actual code, i didn't put brackets.

**Comment by telunc** [comment] 2017-06-15 00:44
I made a pull request for this issue #1596

**Comment by telunc** [comment] 2017-06-15 01:54
You have to look into VoiceChannel's joinable(). The problem is that permissionsFor is not giving the correct values.

```js
this.permissionsFor(this.client.user).has('CONNECT')
```

**Comment by FireController1847** [comment] 2017-06-15 16:31
I've noticed this as well, as well on permissionsFor. I always check if my bot has permission to send messages in the channel and I've gotten multiple errors from that line (in exclusive testing) of bot having permission to send messages.

**Comment by iCrawl** [comment] 2017-06-15 16:50
Found the issue. Gonna be fixed in the next few commits. I'll leave a message and close the issue when its done.
This is only an issue on master btw.

**Comment by MeesMaas** [comment] 2017-06-21 20:12
I experience this issue as well:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: Error: Connection not established within 15 seconds.
    at VoiceConnection.authenticateFailed (/home/mees/MeMezBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:256:26)
    at connectTimeout.client.setTimeout (/home/mees/MeMezBot/node_modules/discord.js/src/client/voice/VoiceConnection.js:277:18)
    at Timeout.setTimeout (/home/mees/MeMezBot/node_modules/discord.js/src/client/Client.js:422:7)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
error: Forever detected script exited with code: 1
error: Script restart attempt #10
```

**Comment by hydrabolt** [comment] 2017-06-24 22:29
Can you see if the above PR (#1601) fixed your issue? Thanks.

**Comment by OkitaSougoo** [comment] 2017-06-27 04:10
@hydrabolt I think the issue is fixed since I don't see any of those errors anymore. Thanks a lot!

**Closed** 2017-07-03 22:25 UTC
Labels: s: unverified, t: voice, type: bug
