### ISSUE TITLE
(indev branch) entrypoint.js crashes on older node versions

### ISSUE THREAD

**Issue by nicholastay** [hydrabolt/discord.js#97] opened 2015-12-15 00:15 UTC
In entrypoint.js it has a message saying that it is not supported by versions < 0.12.7. But even on version 0.12.7, it crashes on this file as it uses the new ES6 template literal for the multiline string. Requiring 'lib/index.js' manually still works as intended as it is all compiled into ES5 past that point.

(audio playback doesn't work properly for me on node >=v4, so I have to stick to 0.12.x)

**Comment by TehSeph** [comment] 2015-12-15 00:23
@nicholastay It's not a bug, it's intentional. 0.12.7 isn't supported.
https://github.com/hydrabolt/discord.js/blob/master/entrypoint.js#L20

Audio playback works fine on 4.x and higher. Your problem must originate from somewhere else.

**Comment by nicholastay** [comment] 2015-12-15 00:25
I am on 0.12.9 now and it still doesn't work. If it is intentional then maybe you should raise the version required even higher? (indev branch I was saying, as template literals don't work on 0.12.x afaik)

**Comment by TehSeph** [comment] 2015-12-15 00:28
Oh, you mean LN22-26 of the indev entrypoint.js is crashing node higher than 0.12.7 and lower than 4.x... I get it now! Yeah nice catch.

**Comment by abalabahaha** [comment] 2015-12-15 02:05
Whoever decided to add a node >= 4 feature into the node < 4 checker (facepalm)

**Comment by SimonSchick** [comment] 2015-12-15 02:27
Yea sorry about that one, I forgot that entrypoint is not babel'd.

**Comment by hydrabolt** [comment] 2015-12-16 16:33
Fixed in 3614b7897312f803f35c15144843a13f7e0c964b

**Closed by hydrabolt** 2015-12-16 16:33 UTC
