### ISSUE TITLE
Issues with reconnection

### ISSUE THREAD

**Issue by MikaalSky** [hydrabolt/discord.js#699] opened 2016-09-13 21:33 UTC
My bot will refuse to reconnect sometimes. It'll get hung in a "reconnect loop" and never comes back online even though discord displays it as online.
![image](https://cloud.githubusercontent.com/assets/6946558/18492240/ce516d8c-79cf-11e6-9510-02e63b976aba.png)
"Got Disconnected" is the message I log on reconnect.

**Comment by MikaalSky** [comment] 2016-09-13 21:36
May not be an actual bug but if someone else can confirm this that would be perfect.

**Comment by GusCaplan** [comment] 2016-09-14 04:40
discord displays the bot as online because you never send it a specific logout message (i assume) and it carries the sessions for a few minutes to iron out connection loss and such. Also, the only way i can reproduce that is by cutting nodejs's websocket off from the internet using firewalls.

**Comment by hydrabolt** [comment] 2016-09-14 15:30
It may not reconnect due to network issues?

**Comment by GusCaplan** [comment] 2016-09-14 18:26
That's what I was inferring

**Comment by MorningSleeper** [comment] 2016-09-14 19:07
Don't know if it is related but I have been getting the following recently when trying to connect:

    Error: getaddrinfo ENOTFOUND gateway.discord.gg gateway.discord.gg:443
        at errnoException (dns.js:28:10)
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
    error: Forever detected script exited with code: 1
    error: Script restart attempt #3
    error: Forever detected script was killed by signal: SIGKILL
    events.js:160
          throw er; // Unhandled 'error' event
          ^

My bot used to connect on first try now it can take as much as 7 tries with the preceding tries returning the above. I went to http://gateway.discord.gg/ and it returned a Cloudflare page with 522 error.

**Comment by Gawdl3y** [comment] 2016-09-14 19:24
@MorningSleeper That's on Discord's end.

**Comment by GusCaplan** [comment] 2016-09-14 20:02
@MorningSleeper gateway.discord.gg isn't a site you can open in your browser, so trying that won't do anything

**Comment by trinitynet** [comment] 2016-09-15 00:21
im not sure if this is related but my on ready emitter will fire, this only seams to happen during audio playback

http://prntscr.com/ci4hnu`

**Comment by hydrabolt** [comment] 2016-09-25 14:04
Fixed in https://github.com/hydrabolt/discord.js/commit/534d7af8c36e3631fb8916a4cac7e5d443b0fd38. Will be available in next release, in the meantime, you can use the indev branch.

**Closed by hydrabolt** 2016-09-25 14:04 UTC
Labels: potential bug
