### ISSUE TITLE
client.UpdateChannel(); updates only once.

### ISSUE THREAD

**Issue by Equinoxbig** [hydrabolt/discord.js#467] opened 2016-07-15 02:09 UTC
So yeah here is my code : 

if (input.startsWith("TOPIC")) {
    text = message.content.split(" ")[1];
    bot.UpdateChannel(message, {topic: text});
}

(input is message.content.toUpperCase();)

and when I use the command it updates once then can't update anymore.

**Comment by GexoXYZ** [comment] 2016-07-15 02:16
Should be fixed on indev

**Comment by abalabahaha** [comment] 2016-07-18 19:19
Dupe of #455

**Closed by abalabahaha** 2016-07-18 19:19 UTC
