### ISSUE TITLE
Stream is not generating quickly enough. 

### ISSUE THREAD

**Issue by Wodki** [hydrabolt/discord.js#1225] opened 2017-02-25 19:45 UTC
Below is the event I use to get how many members are at my voice channel at any given time. My code besides that is simply generating a stream (which works perfectly without it). 

If I add this event I get the error `Stream is not generating quickly enough.` on dispatcher end event. after a few times when members join and/or leave and/or mute and/or unmute themselves, my bots stops playing with no further error. 
```javascript
client.on('voiceStateUpdate', () => {
    if(condition)
    {
        if(dispatcher.paused)
            dispatcher.resume();
    }else
        if(!dispatcher.paused)
            dispatcher.pause();
});
```
I have the latest ffmpeg and I am using indev-prism.

**Comment by hydrabolt** [comment] 2017-02-25 23:19
It means that discord.js isn't able to retrieve audio data fast enough for it to play, which would suggest your download speed is too low (if you're playing from an external file, that is) or that your CPU can't keep up with encoding data.

**Comment by GusCaplan** [comment] 2017-02-26 06:30
please make sure that is the specific event that triggers it. going on a wild goose chase would be quite annoying.

**Comment by wodki2** [comment] 2017-02-26 06:37
I ran the code without that event for 10h yesterday and the error did not appear. After adding the event again though the error reappeared. It might have to do with how fast I am trying to pause and un-pause so I'll add a timeout of about 10s and I'll see what happens.

**Comment by wodki2** [comment] 2017-02-27 08:25
So yeah for sure that event makes my code disconnect. After disconnecting there is no sound when I rejoin. The bot without that part of the code has been running for roughly 24h with no error whatsoever.

**Comment by TimeForANinja** [comment] 2017-03-07 22:00
Also got this Problem, seems to come from `node-ytdl-core` thou, not sure wether u also use it @Wodki

**Comment by trinitynet** [comment] 2017-03-08 16:20
the issue is the pausing, it causes the buffer to terminate if used with `ytdl`, Cant say ive looked into what causes this but ive known of this issue for a long time now

**Comment by iCrawl** [comment] 2017-04-05 19:59
This seems to be related to ytdl-core. I don't have the error when playing a stream that isn't from youtube nor when I use a file.
I'll close this, if the issue persists just request to reopen the issue.

**Closed by iCrawl** 2017-04-05 19:59 UTC
Labels: t: voice, type: discussion
