### ISSUE TITLE
Some members nicknames appear 'undefined'

### ISSUE THREAD

**Issue by PictureGamer** [hydrabolt/discord.js#703] opened 2016-09-14 20:00 UTC
When requesting a member's nickname, I occasionally receive an 'undefined' result even though a nickname is set. This is a different result than requesting a nickname for a member without a nickname, which results in 'null'.

After testing 150+ members, it seems to happen to 5% of users. Anyone know what could cause this?

**Comment by chizdippler** [comment] 2016-09-16 22:32
I found something like this a few days ago while testing a bot I was writing. I was only dealing with a few members, not 150+, but I noticed that when a member initially set their nickname (i.e., username -> nickname) the Discord server/bot instance/whatever it was didn't automatically register that change. So when I tested the bot that member's username returned undefined (not null).

All this to say it might be caused by a nickname change event not firing and those 5% of the members you noticed this on might have changed their nicknames at that time.

**Comment by PictureGamer** [comment] 2016-09-19 14:48
Interesting theory; this could be the case for a few members but there are some that my bot consistently refuses to find the nickname for despite the member not changing their nickname during the search (went through rounds of testing with those affected).

**Comment by Gawdl3y** [comment] 2016-09-19 18:48
Should be fixed in latest indev. (7957bc82cd1890ea8c428abd3d8bf14035222eff)

**Closed by Gawdl3y** 2016-09-19 18:48 UTC
Labels: potential bug
