### ISSUE TITLE
Cannot delete message after sending to message author

### ISSUE THREAD

**Issue by Gawdl3y** [hydrabolt/discord.js#504] opened 2016-08-06 23:01 UTC
Running this code in a `message` event:
```
msg.client.sendMessage(msg.author, 'Testing 123')
    .then(m => m.delete())
    .catch(err => console.log(err));
```

Results in:
```
TypeError: Cannot read property 'queue' of undefined
    at InternalClient.apiRequest (Z:\Projects\Node\discord-rpbot\node_modules\discord.js\lib\Client\InternalClient.js:1:5948)
    at Z:\Projects\Node\discord-rpbot\node_modules\discord.js\lib\Client\InternalClient.js:36:425
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Deleting a direct message always seems to fail when it was sent using the user object. The relevant line of code in discord.js appears to be [src/Client/InternalClient.js:128](https://github.com/hydrabolt/discord.js/blob/master/src/Client/InternalClient.js#L128).

**Comment by GexoXYZ** [comment] 2016-08-06 23:02
Duplicate of https://github.com/hydrabolt/discord.js/issues/496

**Closed** 2016-08-06 23:07 UTC
Labels: bug, duplicate
