### ISSUE TITLE
clientUser.setGame requires type as a parameter via Discord change log

### ISSUE THREAD

**Issue by Lovinity** [hydrabolt/discord.js#1811] opened 2017-08-21 01:51 UTC
**Please describe the problem you are having in as much detail as possible:**
ClientUser.setGame no longer works because Discord announced the requirement of the type field when using that. Discord.js currently does not do the type field.

**Include a reproducible code sample here, if possible:**
```js
ClientUser.setGame('game here');
```

**Further details:**
See August 16 change log at https://discordapp.com/developers/docs/change-log

- discord.js version: 11.1
- node.js version: Unknown
- Operating system: CentOS 7
- Priority this issue should have – please be realistic and elaborate if possible: Urgent; Discord.js' lack of the type field in setGame causes break in functionality.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment] 2017-08-21 01:52
Duplicate of 1807, 1804, 1798

**Closed by iCrawl** 2017-08-21 01:52 UTC
