### ISSUE TITLE
.nsfw not working correctly!

### ISSUE THREAD

**Issue by Ishidres** [hydrabolt/discord.js#2002] opened 2017-10-03 13:56 UTC
**Please describe the problem you are having in as much detail as possible:**
**`message.channel.nsfw`** isn't working how it should as it almost always responds with _false_, even if the channel, the message/command was sent in is marked as nsfw.
For some reason this also only happens in some nsfw-channels and not every.

I also already asked in the discord.js server, but the helpers there told me to open an issue.
Oh yeah, and I've got the latest version of discord.js installed.

**Include a reproducible code sample here, if possible:**
```js
if (command === "test-nsfw") {
  console.log(message.channel.nsfw); // false

  if (message.channel.nsfw === false) {
    return message.reply(":warning: This channel isn't marked as NSFW.");
  }
}
```

**Further details:**

- discord.js version: 11.2.1
- node.js version: 8.6.0
- Operating system: Debian 8
- Priority this issue should have – please be realistic and elaborate if possible: **middle**

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by devsnek** [comment] 2017-10-03 15:08
discord has changed how nsfw channels are marked as nsfw. it is no longer by name (prefixing with `nsfw-`) but by a toggle in the channel settings.

**Comment by Ishidres** [comment] 2017-10-03 16:57
I know and .nsfw checks for those channel settings, right?

**Comment by Dev-Yukine** [comment] 2017-10-03 16:58
I tested around on stable (11.2.1) and can not reproduce this issue.

**Comment by ShayBox** [comment] 2017-10-03 17:00
It used to check for the prefix nsfw in the channel name, but has since switched to checking for the actual nsfw data, if you are having issues you may be running an older version of discord.js, try `npm update`

**Comment by BigBrainAFK** [comment] 2017-10-03 17:10
If you use 11.2.1 or master and it returns false then the channel is not set as an nsfw channel.

Just naimg it nsfw doesnt make it nsfw.

**Comment by ShayBox** [comment] 2017-10-03 17:15
Actually it does 😉 
![3doxa](https://user-images.githubusercontent.com/9505196/31138533-d533bc44-a83c-11e7-99c9-ef61697718e3.gif)

**Comment by BigBrainAFK** [comment] 2017-10-03 17:16
> Actually it does

all my old nsfw channels arent nsfw despite still having the old nsfw tag

**Comment by devsnek** [comment] 2017-10-03 17:19
@ShayBox what you're seeing is a choice the client makes to patch nsfw: true when you name it with nsfw, but old channels that were nsfw by name won't be nsfw by property so they won't show up as nsfw.

**Closed** 2017-10-04 08:58 UTC
Labels: s: invalid
