### ISSUE TITLE
ReactionAdd event ignores old messages even if the bot is running on a bot account

### ISSUE THREAD

**Issue by meldsza** [hydrabolt/discord.js#1675] opened 2017-07-10 03:56 UTC
The code at 
https://github.com/hydrabolt/discord.js/blob/master/src/client/actions/MessageReactionAdd.js
Ignores messages that haven't been already cached. So if I want to listen to message reactions that were sent before my not restarted, I would not be able to.

**Further details:**

- discord.js version: master
- node.js version: 7.8
- Operating system: CentOs
- Priority: 5/10

I found this issue while running code on a **bot account**

- [x] I have also tested the issue on latest master, commit hash:

**Comment by dragonfire535** [comment] 2017-07-10 04:23
Indeed, you will have to fetch any messages not in cache for events to fire.

**Comment by Drahcirius** [comment] 2017-07-10 04:26
This is currently the expected behaviour, Currently, #1376 is on the roadmap for v12, which will allow you to receive previously uncached reaction events with a client setting.

**Comment by meldsza** [comment] 2017-07-10 04:36
Is there a separate branch for v12 i can contribute to?

**Comment by Drahcirius** [comment] 2017-07-10 04:59
Master branch is v12. Contributions are welcome, but I will be submitting a PR for it soon.

**Comment by iCrawl** [comment] 2017-08-01 02:36
Duplicate of #1376

**Closed by iCrawl** 2017-08-01 02:36 UTC
Labels: p: low, t: REST, type: enhancement
