### ISSUE TITLE
addRoles and removeRoles return the member before the change

### ISSUE THREAD

**Issue by AppleBetas** [hydrabolt/discord.js#1281] opened 2017-03-16 17:46 UTC
On GuildMember, unlike addRole and removeRole, when using addRoles or removeRoles, the member returned in the promise is the one from before the roles were changed. You can tell this because the roles on the member are the same as before the roles were changed.

**Comment by iCrawl** [comment] 2017-03-16 17:47
Stable? Master?

**Comment by AppleBetas** [comment] 2017-03-16 17:48
Sorry, this is on stable

**Comment by iCrawl** [comment] 2017-03-16 17:49
Can you install master and try again, please?

**Comment by AppleBetas** [comment] 2017-03-16 17:52
Again, sorry, but how do I tell npm which to install?

**Comment by iCrawl** [comment] 2017-03-16 17:54
`npm i -S hydrabolt/discord.js`

**Comment by AppleBetas** [comment] 2017-03-16 17:56
It does still occur

**Comment by bdistin** [comment] 2017-04-10 14:05
I can no longer reproduce this bug on master.

**Comment by bdistin** [comment] 2017-04-10 14:09
I can no longer reproduce this bug on Master. (Checked a second method since the original deleted comment)

**Comment by Ghostaunt** [comment] 2017-04-14 14:40
Same issue here roles are not refresh

**Comment by iCrawl** [comment] 2017-04-14 20:14
Are you on latest master?

**Comment by Ghostaunt** [comment] 2017-04-14 20:22
Yes

**Comment by hydrabolt** [comment] 2017-08-25 22:44
Fixed in master, will close when the next version is released.

**Comment by hydrabolt** [comment] 2017-09-05 16:18
Closing early

**Closed by hydrabolt** 2017-09-05 16:18 UTC
Labels: p: medium, s: fixed on master, t: caching, type: bug
