### ISSUE TITLE
guildMember.setMute() is not functional sometimes

### ISSUE THREAD

**Issue by PhoenixShay** [hydrabolt/discord.js#1742] opened 2017-08-01 15:52 UTC
**Please describe the problem you are having in as much detail as possible:**

guildMember.setMute() does not work reliably. Sometimes it will not work on any user at all, and the process will have to be restarted. I've tried to set the mute of someone up to 5 times (delayed of course) and absolutely nothing happens.

**Include a reproducible code sample here, if possible:**
It isn't reproducible. There's no errors in console when this happens, it just straight up doesn't do anything.

**Further details:**

- discord.js version: Master
- node.js version: 8.0.0
- Operating system: Ubuntu 16.04
- Priority this issue should have – please be realistic and elaborate if possible: Medium, this can affect moderation bot features.

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: a46f606170755b6bf024256625544040ced6921c

**Comment by evaera** [comment] 2017-08-01 15:54
Can confirm this happens often, experienced it myself, even when explicitly calling setMute via an eval debug command, independent of all other bot code. It will mute some users, and others it won't work at all.

**Comment by SpaceEEC** [comment] 2017-08-01 16:03
If the targetted member is not currently in a voice channel the request will go through but the user won't be muted/unmuted, (same for deafening).

This is a limitation on discord's side as they simply discard those requests silently and respond with a 204 nevertheless.

You both didn't mention whether the target is in a voice channel when attempting to muting them, so I assumed that this could be the cause for your issue.

**Comment by PhoenixShay** [comment] 2017-08-01 16:35
My bad. They **are** in a voice channel at the time of muting.

**Comment by hydrabolt** [comment] 2017-08-25 22:47
Can you guys test this again? I did a pretty big overhaul and state, and voice state was one of the things I fixed.

**Comment by PhoenixShay** [comment] 2017-08-25 23:59
I will test it in a bit, do you have a discord I could talk to you at?

**Comment by hydrabolt** [comment] 2017-08-26 00:14
hydrabolt#0086, there's a link to our discord.js server in the readme

**Comment by hydrabolt** [comment] 2017-09-04 12:23
I'm assuming this is fixed now, if it's not, then re-open the issue

**Closed by hydrabolt** 2017-09-04 12:23 UTC
Labels: s: potentially fixed, s: unverified, t: REST, t: voice, type: bug
