### ISSUE TITLE
RangeError: index out of range

### ISSUE THREAD

**Issue by manmon42** [hydrabolt/discord.js#236] opened 2016-03-27 09:09 UTC
When I try and play an audio file over the voice chat, it throws this error.
```
buffer.js:625
    throw new RangeError('index out of range');
    ^

RangeError: index out of range
    at checkOffset (buffer.js:625:11)
    at Buffer.readInt16LE (buffer.js:760:5)
    at Volume._transform (d:\Desktop\Discord-App-2\node_modules\discord.js\lib\Voice\VolumeTransformer.js:3:46)
    at Volume.Transform._read (_stream_transform.js:166:10)
    at Volume.Transform._write (_stream_transform.js:154:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
    at Volume.Writable.write (_stream_writable.js:215:11)
    at Socket.ondata (_stream_readable.js:528:20)
    at emitOne (events.js:77:13)
```

This is the important bit of code. The channel var is set earlier in the code.

```js
mybot.joinVoiceChannel(channel, function (err, connection){
                if(err) {
                    console.error("Error joining Voice Channel:\n   " + err);
                }
                connection.playFile('Super Mario Bros.-Coin Sound Effect.mp3', function(err){
                    if(err){console.log("Play err \n  " + err)}
                });
            });
```

**Comment by abalabahaha** [comment] 2016-03-27 09:46
Duplicate of #193, I'll reopen that

**Closed by abalabahaha** 2016-03-27 09:46 UTC
Labels: duplicate
