### ISSUE TITLE
`setStatus` and other status changing functions seem broken.

### ISSUE THREAD

**Issue by NightmareX91** [hydrabolt/discord.js#143] opened 2016-01-13 15:39 UTC
Upon the use of `bot.setStatus("away");`, I expect the client to change its status to `away`. However, this does not happen. No errors are printed to the log.
Functions such as `setStatusIdle` also fail to set the client's status.

The last time I tried this function was on `5.2.0` and it worked, but on `5.3.2` it doesn't seem to work.

**Comment by OneMansGlory** [comment] 2016-01-13 15:40
Mine as well.

**Comment by OneMansGlory** [comment] 2016-01-13 15:41
Mine crashes with an error to console. I will send screens/more info later.

**Comment by khionu** [comment] 2016-01-13 15:53
I'm using 5.3.2 and I can confirm that setting to `Away` doesn't work. No crash/error, just fails.

**Comment by TehSeph** [comment] 2016-01-13 17:46
More than likely fixed with [8a8ba51](https://github.com/hydrabolt/discord.js/commit/8a8ba51c2b77711c860dd62e8db0e613959a30a4) since for some reason the code in `5.3.2` tried to set the packet before it even existed and the definition was overwritting it with the current idle status.

If anyone is willing to test the latest indev, does that fix it?

**Comment by NightmareX91** [comment] 2016-01-13 19:18
`setStatus` works in the latest indev.

**Closed** 2016-01-13 19:19 UTC
Labels: bug, potentially fixed

**Comment by BourKeeg815** [comment] 2017-06-25 22:42
The actual command would be this.client.setStatus("away")

**Comment by EllenFawkes** [comment] 2017-09-25 14:15
Hi. iIhave a problem with setStatus(). function nothing do. i set status to `dnd` but status is still `online`. I used it with setGame(). I tried use it single without setGame() and this take the same effect. setGame() sets the game OK.

```javascript
this._client.user.setStatus("dnd");
this._client.user.setGame(`${type} - ${msg}`);
```
NOTE: `this._client` is my instance of Discord.Client

**Comment by devsnek** [comment] 2017-09-25 14:33
@EllenFawkes you should update to the latest version (11.2.1 at the time of this posting)

**Comment by EllenFawkes** [comment] 2017-09-25 14:41
@devsnek Yes, I already updated to version 11.2.1 and setStatus not working.

**Comment by robflop** [comment] 2017-09-25 17:10
@EllenFawkes Are you sure nothing is happening and that there are no errors or anything? I've just tried this on version 11.2.1 and it works flawlessly.
