### ISSUE TITLE
UnhandledPromiseRejectionWarning when using special characters in a message

### ISSUE THREAD

**Issue by monodokimes** [hydrabolt/discord.js#2207] opened 2017-12-31 19:11 UTC
`member.send()` is producing this warning message when trying to send a message that includes characters such as * or `, required for Markdown formatting.
```
(node:12328) UnhandledPromiseRejectionWarning: DiscordAPIError: Cannot send messages to this user
    at item.request.gen.end (/home/cat/projects/bots/gary/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:68:65)
    at then (/home/cat/projects/bots/gary/node_modules/snekfetch/src/index.js:183:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:12328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```js
// Produces message
member.send('a*').catch(console.error);
// Does not produce message
member.send('a').catch(console.error);
```

- discord.js version: 11.2.1
- node.js version: 9.3.0
- Operating system: Linux 4.14.9-1-ARCH
- Priority this issue should have – please be realistic and elaborate if possible: Low, doesn't affect actual performance. Production of warning message is annoying.

**EDIT:** Updated discord.js version

**Comment by dragonfire535** [comment] 2017-12-31 19:15
Can you update snekfetch and discord.js and see if the issue persists?

**Comment by devsnek** [comment] 2017-12-31 19:21
discord also has filters for spam with dms which might prevent messages of certain kinds from being sent. you could be hitting that, although admittedly I don't know very much about the filters.

**Comment by monodokimes** [comment] 2018-01-01 15:09
Redid all my dependencies. Discord.js version 11.1.2, snekfetch version 3.6.1. Issue persists.

**Comment by devsnek** [comment] 2018-01-01 20:12
i can't reproduce on master with snekfetch 3.6.1

**Comment by Lewdcario** [comment] 2018-01-15 20:32
Closing since this seems to be dead and otherwise unable to be reproduced.

**Closed by Lewdcario** 2018-01-15 20:32 UTC
Labels: p: medium, s: unverified, t: REST, type: bug
