### ISSUE TITLE
guild.member.nickname crashes rather then returning null or undefined if member has no nickname

### ISSUE THREAD

**Issue by GNUGradyn** [hydrabolt/discord.js#1167] opened 2017-02-04 00:37 UTC
This is a snippet of code running inside a message listener:
```
 if (message.content == "/gradyncore experiment") {
  message.channel.sendMessage(message.guild.member(message.author).nickname)
 }
```
Upon running /gradyncore experiment with a nickname, it returns my nickname. However, if I don't have a nickname, it crashes with the following error:
```
/home/gradyn/gradyncore/gradyncore/node_modules/discord.js/src/structures/interface/TextBasedChannel.js:75
    if (options.file) {
               ^

TypeError: Cannot read property 'file' of null
    at TextChannel.send (/home/gradyn/gradyncore/gradyncore/node_modules/discord.js/src/structures/interface/TextBasedChannel.js:75:16)
    at TextChannel.sendMessage (/home/gradyn/gradyncore/gradyncore/node_modules/discord.js/src/structures/interface/TextBasedChannel.js:110:17)
    at Client.client.on.message (/home/gradyn/gradyncore/gradyncore/gradyncore.js:107:19)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (/home/gradyn/gradyncore/gradyncore/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/gradyn/gradyncore/gradyncore/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:120:65)
    at WebSocketManager.eventMessage (/home/gradyn/gradyncore/gradyncore/node_modules/discord.js/src/client/websocket/WebSocketManager.js:272:31)
    at WebSocket.onMessage (/home/gradyn/gradyncore/gradyncore/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)

```

**Comment by GusCaplan** [comment] 2017-02-04 01:05
the fix for this would be `if (!content) return` internally, at which point we could also just tell you not to try to send `null` kthx

**Comment by GNUGradyn** [comment] 2017-02-04 01:11
Umm.. no.. that doesn't work, because it STILL will try to get the nickname from the author. And since the author doesn't have a nickname, and discord.js doesn't know how to handle the absence of a nickname, so it crashes.

**Comment by Gawdl3y** [comment] 2017-02-04 02:32
No, `member.nickname` is in fact returning `null` when they don't have a nickname. The problem is you're immediately passing it to `sendMessage`, with `null`. `sendMessage` sees that `typeof null === 'object'`, and tries to access a property on it. Basically, don't pass `null` to `sendMessage`.

**Closed by Gawdl3y** 2017-02-04 02:32 UTC
Labels: s: invalid
