### ISSUE TITLE
bot gets stuck typing

### ISSUE THREAD

**Issue by macdja38** [hydrabolt/discord.js#440] opened 2016-06-25 04:20 UTC
bot sometimes get's stuck sending typing state. Using my eval and calling the stop typing did not fix it... restarting did.

**Comment by developerCodex** [comment] 2016-07-15 21:18
@macdja38 Hey, that's weird because it works perfectly fine for me. What are you typing into your eval so, I may know what the problem is may I have the script for the startTyping and the stopTyping?

**Comment by developerCodex** [comment] 2016-07-15 21:21
@macdja38 Also, can I get an update if you fixed this issue or not. Because it seems like you haven't said anything or mentioned anything in this issue statement for like 21 days+.

**Comment by abalabahaha** [comment] 2016-07-15 21:25
"works fine for me" does not mean the bug doesn't appear for other users. I think there are a few potential places where this could happen, will check later.

**Comment by macdja38** [comment] 2016-07-15 21:29
I cannot confirm nor deny that it's still an issue, but I don't believe anythings been changed since then so I doubt it is. The code that calls it is the cleverbot code is https://github.com/macdja38/pvpcraft/blob/master/modules/cleverBot.js#L26-L32 Which would fail unable to send the message however in that case sending another message or calling stopTyping from eval should fix it. 

When it happened it was only able to be stopped by restarting the bot.

The issue is however very rare. I've only had about 6 reports of it happening accross a bot on thousands of servers with cleverbot as a promenent feature.

**Comment by developerCodex** [comment] 2016-07-15 21:40
@macdja38 Do you have the indevelopment verison of discord.js?

**Comment by developerCodex** [comment] 2016-07-15 21:42
@macdja38 Do you run these things in your eval command: mybot.startTyping(message)
or whatever your bot thing is and to stop it do you run mybot.stopTyping(message)? If so then that's a bug. But if you don't then you should probably test it because it does work on my bot and other bots I have owned.

**Comment by developerCodex** [comment] 2016-07-15 21:44
Okay, so I checked out your js file and just try to use a eval command not any functions or anything in your .js file.

**Comment by macdja38** [comment] 2016-07-15 21:48
Yes, I have the indev version of discord.js, though atm I'm using my own fork that handles rate limits a bit differently but this was occuring before that while I was on the old indev, which has since become master, I was running client.stopTyping(channel) as stated http://discordjs.readthedocs.io/en/latest/docs_client.html#stoptyping-channel-callback in the docs. There have been no changes recently to my knowlege however that effect the typing state system.

Internally discord.js uses a setInterval to send packets telling discord it's still typing in that channel, I believe what may be happening is that reference to the timeout is being overwriten, and it's unable to stop the timer.

**Comment by developerCodex** [comment] 2016-07-15 21:57
Oh, your using the wrong one.
You do client.stopTyping(message) and to start you use client.startTyping(message) as I know of now.

**Comment by macdja38** [comment] 2016-07-15 22:00
Did... did you actually click the link I sent...

**Comment by developerCodex** [comment] 2016-07-15 22:26
Yes, ;)

**Comment by developerCodex** [comment] 2016-07-15 22:26
Just let abal take over this.

**Comment by macdja38** [comment] 2016-07-15 22:27
The doc's clearly state that client.stopTyping(channel) is a valid way to stop the bot from typing and it works 99.9% of the time.

**Comment by macdja38** [comment] 2016-08-11 19:08
I can confirm this does still happen with the latest indev as of now.

**Comment by hydrabolt** [comment] 2016-09-04 14:44
Fixed in [9.0.2](https://github.com/hydrabolt/discord.js/releases/tag/9.0.2)

**Closed by hydrabolt** 2016-09-04 14:44 UTC
Labels: bug
