### ISSUE TITLE
on voiceLeave returns ServerChannel instead

### ISSUE THREAD

**Issue by Raus-z** [hydrabolt/discord.js#254] opened 2016-04-07 01:30 UTC
I came across this bizarre bug with on voiceLeave.
I have three identical voice channels all named the same thing. In a normal situation, when a user joins one of these channels, the bot's on voiceJoin triggers properly returning the VoiceChannel object.
For some apparent reason though, on voiceLeave fails horribly and return the ServerChannel object instead of the VoiceChannel object.
Even further stranger still, when the bot's Manage Permissions perm is removed, it properly returns the VoiceChannel object for these three voice channels; Other voice channels work fine and are unaffected by the Manage Permissions perm.
And one last thing I noticed, the culprit voice channels only trigger on voiceLeave if you completely disconnect, not just switch voice channels. The other voice channels will trigger on voiceLeave if you switch to another channel.

Here's the relevant code:
`mybot.on("voiceLeave", function(voice, user) {
	console.log(voice.id);
	console.log(voice.name);
	console.log(voice);
});`

Running Node.js v4.3.1, Discord.js v6.1.0 on Windows 10

**Comment by Programmix** [comment] 2016-05-30 15:03
Is this bug still prevalent?

**Comment by GexoXYZ** [comment] 2016-06-26 05:08
Cannot reproduce. May have also been fixed with `voiceSwitch` https://github.com/hydrabolt/discord.js/commit/05def5b3f2dff76a4b708d6085e9f777bd89c96a

**Closed** 2016-06-26 06:23 UTC
Labels: bug
