### ISSUE TITLE
DiscordAPIError: Undefined when changing profile image

### ISSUE THREAD

**Issue by Sven65** [hydrabolt/discord.js#1784] opened 2017-08-16 17:23 UTC
**Please describe the problem you are having in as much detail as possible:**

Tried to change the profile picture of my account, got an error;

```js
{ DiscordAPIError: undefined
    at item.request.gen.end (D:\Users\Mackan\Documents\GitHub\test\Discord Pic Rotator\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:68:65)
    at then (D:\Users\Mackan\Documents\GitHub\test\Discord Pic Rotator\node_modules\snekfetch\src\index.js:257:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  name: 'DiscordAPIError',
  message: 'undefined',
  code: undefined }
```

**Include a reproducible code sample here, if possible:**
```js
client.on("ready", () => {
	console.log(`Logged in as ${client.user.tag}.`)
	fs.readdir(imageDir, (err, files) => {
		if(err){
			throw err
		}

		let fileName = files.random()

		console.log(`Selected file ${fileName}.`)

		console.log("Changing avatar...")

		client.user.setAvatar(`${imageDir}/${fileName}`).then(() => {
			console.log("Avatar changed!")
			client.destroy()
		}).catch(console.error)
	})
})
```

**Further details:**

- discord.js version: 11.1.0
- node.js version: 7.7.3
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: Low/Medium

- [x ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:

**Comment by iCrawl** [comment] 2017-08-16 17:28
Duplicate of #1725

**Closed by iCrawl** 2017-08-16 17:28 UTC
