### ISSUE TITLE
Typo causes crash.

### ISSUE THREAD

**Issue by tehkhop** [hydrabolt/discord.js#209] opened 2016-03-11 03:57 UTC
lib/Client/InternalClient.js:1147

InternalClient::updateDetails();

if(!email) used instead of if(!this.email) for checking if token was used.

**Comment by Lord-Ptolemy** [comment] 2016-03-11 04:24
https://github.com/hydrabolt/discord.js/blob/indev/src/Client/InternalClient.js#L1006
Already fixed in indev: 8d59498

**Closed** 2016-03-11 05:23 UTC

**Comment by abalabahaha** [comment] 2016-03-11 05:27
Duplicate of 8d59498 #176 #187 #203 #207 

Yes, NPM/master don't have this patch released yet. However, that still doesn't mean it isn't already fixed in development (indev branch).

**Comment by tehkhop** [comment] 2016-03-11 07:07
Apologies.
