### ISSUE TITLE
End Event Being Received Twice On Debian

### ISSUE THREAD

**Issue by Raserhead** [hydrabolt/discord.js#2132] opened 2017-11-24 08:09 UTC
**Please describe the problem you are having in as much detail as possible:**
For a little while I had been working on a skip command for my music player, on windows the code runs fine with no problems, however after deploying my code onto linux, any time `voiceChannel.connection.dispatcher.end()` is used the "end" event seems to be sent/received twice. I have logged some messages to display the flow of code.

> Calling Skip
>Sending End Method (`voiceChannel.connection.dispatcher.end()`)
>End Event Received (`.on('end')`)
>http://www.youtube.com/watch?v=MBdVXkSdhwU (Next item in array)
>End Event Received (`.on('end'`)
>undefined (Next item in array is empty)

Since the next item is empty, it then exits.

**Include a reproducible code sample here, if possible:**
Copying the whole code would be a bit much, more or less the flow is:
>1. Array with some links
>2. Get first link from Array
>3. Play link using ytdl-core & `voiceChannel.voiceConnection.playStream()`
>4. `voiceChannel.connection.dispatcher.end()` is called through "skip" command.
>5. 'end' event received.
>6. Link is removed from array.
>7. Go back to 2.

But instead, the end event is received twice and removes 2 links.
However, if the dispatcher ends "naturally" (the song ending) the end event is only received once.

If you would like the code itself, I can do that.

**Further details:**

- discord.js version: 11.2.1 (Windows uses the same)
- node.js version: 8.7.0 (Windows 8.6.0)
- Operating system: Debian 9.1 Stretch 64bit (Windows 7 Ultimate 64bit)
- Priority this issue should have – please be realistic and elaborate if possible: Since I'm not absolutely certain it's not an install issue, as I did have some hiccups.  A relatively normal priority should be fine.

- [ ] I found this issue while running code on a __user account__
- [ ] I have also tested the issue on latest master, commit hash:
I am uncertain of the 2nd one.

**Comment by Raserhead** [comment] 2017-11-24 08:22
I just noticed there was an issue that sounds extremely similar below and I just had not noticed because the title seemed just different enough to possibly not be relevant, I'm going to thoroughly read through it now.

**Comment by Raserhead** [comment] 2017-11-24 08:36
So I've just found out why it worked on windows and not debian, the discord server is US based so my ping to it will be larger than what the ping would be for the also US based VPS the bot is on. So my ping literally acted as a delay for the command. After reading the other issue I mentioned above, it's not "fixed fixed" but I have "replicated" the delay that I would get from the ping as a timeout in the command.

I'll leave it up to whoever moderates as to whether to close this or not.

**Comment by appellation** [comment] 2017-11-24 09:43
See #1387

**Comment by Raserhead** [comment] 2017-11-24 10:28
Yeah, that's the issue I referred to earlier.

**Comment by iCrawl** [comment] 2017-11-24 15:48
Can you install prism via github: `npm i hydrabolt/prism-media` it should be fixed there.

**Comment by thomasxd24** [comment] 2017-12-05 21:24
in master branch they fixed the issue, maybe consider updating to master

**Comment by iCrawl** [comment] 2017-12-12 04:15
Duplicate of #1387

**Closed by iCrawl** 2017-12-12 04:15 UTC
Labels: s: duplicate
