### ISSUE TITLE
GuildMembers Presence not working on latest master

### ISSUE THREAD

**Issue by FireController1847** [hydrabolt/discord.js#2058] opened 2017-10-25 03:11 UTC
**Please describe the problem you are having in as much detail as possible:**
When fetching guild member's presence, two completely different numbers show up form the latest master and an old version. Both m.presence and m.user.presence gave the similar big-low ratio.

The version used that gives correct guild count: 243ff48a67446fba96da91503670cea0aba3a968
The version used that does not give correct guild count: ee1d4c53f2770b5e4748d0d7402dc0291f9f869e

**Include a reproducible code sample here, if possible:**
```js
message.channel.send(message.guild.members.size);
```

**Further details:**
IMAGES!!!!!

Old Bot: 
![](https://imgur.com/5aswv51.png)

New Bot:
![](https://imgur.com/qL9wKR9.png)

- discord.js version: Listed Above
- node.js version: v8.7.0
- Operating system: Windows 10
- Priority this issue should have – please be realistic and elaborate if possible: High

- [ ] I found this issue while running code on a __user account__
- [x] I have also tested the issue on latest master, commit hash: ee1d4c53f2770b5e4748d0d7402dc0291f9f869e

**Comment by devsnek** [comment] 2017-10-25 03:20
m.user.presence and m.presence are **VERY** different. `User#presence` is actually a getter which searches all available member objects that user is associated with to find a presence, so it makes sense that more would be found.

**Comment by FireController1847** [comment] 2017-10-25 03:20
They both did it

**Comment by appellation** [comment] 2017-10-26 02:05
Sounds like a duplicate of #1870

**Comment by kyranet** [comment] 2017-10-28 11:31
I can reproduce this aswell. Same results from GuildMember.presence and User.presence. Even `presence.client` is undefined.
![image](https://user-images.githubusercontent.com/24852502/32133999-16727ce4-bbe4-11e7-81ef-02b8f425e543.png)

Additionally, that user has been cached for entire hours.

Commit hash: `296046dbc6faa0b6aeabd0c7efdc470c0c834b16`

**Closed** 2017-10-28 17:03 UTC
