### ISSUE TITLE
Cannot read property 'handle' of undefined on all minified webpack builds

### ISSUE THREAD

**Issue by yuta0801** [hydrabolt/discord.js#1836] opened 2017-08-26 13:53 UTC
~~Sorry, I accidentally press the Enter key to post issues. Please wait for finish writing. Thank you.~~
_The original issue was solved, so please read the message below_

**Comment by iCrawl** [comment] 2017-08-26 14:05
Feel free to use 11.1-dev in the webpack branch, everything works correctly there.
I'm not sure what exactly is wrong with 11.1.0, since it also doesn't throw an error. It just stops at identifying with the gateway. So this needs a bit more investigation.

11.1-dev works correctly though.
![](https://a.safe.moe/1p62t.png)

**Comment by yuta0801** [comment] 2017-08-26 14:06
Thank you.

**Comment by yuta0801** [comment] 2017-08-26 14:24
I tried `discord.11.1-dev.js` and `discord.11.1-dev.min.js`.

Both are Client.user is null.
and `min.js` get error `Cannot read property 'handle' of undefined`.

**Comment by iCrawl** [comment] 2017-08-26 14:24
What browser are you using?

**Comment by yuta0801** [comment] 2017-08-26 14:25
The latest version Google Chrome

**Comment by iCrawl** [comment] 2017-08-26 14:32
I tested this on Chrome `Version 62.0.3192.0 (Official Build) dev (64-bit)` dev
and `Version 60.0.3112.113 (Official Build) (64-bit)` stable

And it works perfectly fine with `discord.11.1-dev.min.js`

Can I see your code?

**Comment by yuta0801** [comment] 2017-08-26 14:35
Sorry, I forgot to await ready event.

The original issue was solved,
but I confirmed `Cannot read property 'handle' of undefined` error in `min.js`.

```
Uncaught TypeError: Cannot read property 'handle' of undefined
    at r.handle (discord.11.1-dev.min.js:1)
    at r.handle (discord.11.1-dev.min.js:1)
    at h.onPacket (discord.11.1-dev.min.js:1)
    at h.onMessage (discord.11.1-dev.min.js:1)
```

**Comment by iCrawl** [comment] 2017-08-26 14:38
This seems to be an issue with the minified file.

I cannot reproduce this on 11.1-dev though. Only on 11.1-dev.min

**Comment by yuta0801** [comment] 2017-08-26 14:41
Noted with thanks.

**Comment by iCrawl** [comment] 2017-09-05 17:42
This should be finally fixed now. All minified webpacks have been updated 👍

**Closed by iCrawl** 2017-09-05 17:42 UTC
Labels: meta: webpack, p: medium, t: gateway, type: bug

**Comment by kenma9123** [comment] 2018-01-26 09:03
still happening on discord.js 11.3.0

**Comment by wjohnsto** [comment] 2018-11-27 15:52
This is happening on 11.4.2:

```
TypeError: Cannot read property 'handle' of undefined
    at t.exports.handle (/srv/index.js:1:396342)
    at t.exports.handle (/srv/index.js:1:382627)
    at l.onPacket (/srv/index.js:1:377444)
    at l.onMessage (/srv/index.js:1:376836)
    at v.n (/srv/index.js:1:414974)
    at emitOne (events.js:116:13)
    at v.emit (events.js:211:7)
    at t.exports._receiver.onmessage.t [as onmessage] (/srv/index.js:1:403076)
    at t.exports.dataMessage (/srv/index.js:1:422707)
    at t.exports.getData (/srv/index.js:1:421963)
```

**Comment by iCrawl** [comment] 2018-11-27 16:09
Yes, this most likely won't be fixed until we release a new version.

Use https://github.com/discordjs/discord.js/blob/webpack/discord.11.4-dev.min.js instead.

It is non-breaking to the current stable release.

**Comment by strass** [comment] 2019-06-21 18:42
I'm hitting this same issue on 11.5.1 - all prod builds by webpack fail and I have to use a development bundle

**Comment by ScarletMetal** [comment] 2019-07-03 04:40
so is there any progress on this issue? I too encountered this issue on 11.5.1

**Comment by edusperoni** [comment] 2019-07-11 14:36
As a workaround, set `keep_classnames: true` in your terser options.

```
new TerserPlugin({
    terserOptions: {
        keep_classnames: true
    }
})
```

**Comment by shanjii** [comment] 2020-08-07 05:31
Just came across this issue trying to run on a production build, development works fine. Version 12.2.0

**Comment by soryy708** [comment] 2021-02-14 11:06
Version 12.5.1 in prod fails with `Cannot read property 'handle' of undefined`. No issues in development.
Why is this issue closed?

**Comment by advaith1** [comment] 2021-02-14 11:08
webpack isn't supported anymore anyway, as Discord no longer allows bot API requests from the browser

**Comment by soryy708** [comment] 2021-02-14 13:56
I use webpack to transpile cutting-edge JS for older NodeJS execution environments. While I could use Babel directly, why would DiscordJS care if there's webpack in the toolchain (if webpack uses Babel behind the scenes)?

**Comment by iCrawl** [comment] 2021-02-14 14:06
We don't. The Terser plugin is at fault here, read above for a solution that works.

**Comment by M1raclee** [comment] 2021-03-14 12:13
Got a similar error with webpack-obfuscator (javascript-obfuscator).
Error appears after send message to discord channel (But message correctly sended)

```
(node:17908) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'handle' of undefined
    at *path_to_project*\index.js:2:270264
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
    
As i understand, problem in response (200), that parsing after discord API send.
If i comment parseResponse in discord.js/rest/requesthandler.js - error not appear.

Any ideas for fix?

**Comment by kyranet** [comment] 2021-03-14 14:39
We have dropped webpack support (and web builds with it) due to the amount of issues that come from them. Although the removal applies to v13, its support for v12 is deprecated, and therefore, not supported.
