### ISSUE TITLE
All websocket messages suddenly stop

### ISSUE THREAD

**Issue by Hackzzila** [hydrabolt/discord.js#1370] opened 2017-04-11 17:43 UTC
Randomly, on latest master, all websocket messages in and out stop. No debug events, no errors, no disconnects, nothing.

**Comment by GusCaplan** [comment] 2017-04-11 19:19
yes. this we can debug. 100%. this is all of the information we need to fix this. 🙃

**Comment by iCrawl** [comment] 2017-04-11 20:05
Duplicate of #1233

**Closed** 2017-04-11 20:05 UTC
Labels: s: duplicate
