### ISSUE TITLE
client.setStatus() Not setting status correctly. & client.setStatusOnline() & client.setStatusIdle() 

### ISSUE THREAD

**Issue by Lord-Ptolemy** [hydrabolt/discord.js#147] opened 2016-01-15 03:00 UTC
Discord.js: NPM 5.3.2
Node: LTS 4.2.3

```javascript
if (mSplit[1] === 'setStatus') {
                            bot.setStatus(mSplit[2], 'test', function(err) {
                                if (err) {
                                    bot.sendMessage(message, 'Dun goofed: ' + err);
                                    console.log(err);
                                    return;
                                }
                                //bot.sendMessage(message, 'Status: ' + mSplit[2] + ' Game: test');
                                console.log('Status: ' + mSplit[2] + ' Game: test');
                            });
                        }
```
The game is set, but the status is not. It will stay as "online" even when you attempt to set it to "away".

Also
client.setStatusOnline() & client.setStatusIdle() both do not set the statuses. Nor do they error.

**Comment by abalabahaha** [comment] 2016-01-15 04:17
Duplicate of #142

**Closed by abalabahaha** 2016-01-15 04:17 UTC

**Comment by khionu** [comment] 2016-01-15 04:32
@abalabahaha umm.... I fail to see how those two issues are similar.... mistyped the issue number maybe?

**Comment by abalabahaha** [comment] 2016-01-15 06:20
@khionu I edited it about 5 seconds after I posted that... are you relying on the email notification?

**Comment by khionu** [comment] 2016-01-15 06:52
No, I wasn't. I blame Chrome 64-Bit's cache. It's been really bad since I upgraded it to 64-Bit.
