### ISSUE TITLE
stream dispatcher: Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by OkitaSougoo** [hydrabolt/discord.js#1579] opened 2017-06-09 22:49 UTC
**Please describe the problem you are having in as much detail as possible:**
I have am getting the following issue of the streamDispatcher `TypeError: Cannot read property 'key' of undefined`. I am wondering if there is any way to solve this issue. Thanks!

**Further details:**
![image](https://user-images.githubusercontent.com/26083763/26996882-5b480d76-4d2a-11e7-9ee8-99824a10378a.png)

- discord.js version: master
- node.js version: 8.0.0
- Operating system: windows 10

- [ ] I have also tested the issue on latest master, commit hash:

**Comment by OkitaSougoo** [comment] 2017-06-11 22:14
I don't seem to find this issue when developing locally, and it only shows up on production ;O

**Comment by aemino** [comment] 2017-06-12 01:27
This issue is a duplicate of #1499. Please refer there.

**Closed** 2017-06-12 10:17 UTC
Labels: s: duplicate
