### ISSUE TITLE
editing a message with an reaction seem to result in undefined error

### ISSUE THREAD

**Issue by frzyc** [hydrabolt/discord.js#1127] opened 2017-01-22 20:27 UTC
```
client.on('message', message => {
    if (message.content === 'testedit') {
        message.reply('testing emoji edit').then(msg => {
            msg.react('😀').then((msgreaction) => msgreaction.message.edit('test test test'));
        })
    }
})
```
this will always give error
```
Uncaught Promise Error:
TypeError: Cannot read property 'name' of undefined
    at new MessageReaction (...\node_modules\discord.js\src\structures\MessageReaction.js:34:48)
    at Message.patch (...\node_modules\discord.js\src\structures\Message.js:235:34)
    at MessageUpdateAction.handle (...\node_modules\discord.js\src\client\actions\MessageUpdate.js:14:17)
    at __dirname.updateMessage.content.rest.makeRequest.then.data (...\node_modules\discord.js\src\client\rest\RESTMethods.js:137:55)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by meew0** [comment] 2017-01-22 21:59
Thanks for reporting, however this appears to be a duplicate of #1071.

**Closed by meew0** 2017-01-22 21:59 UTC
