### ISSUE TITLE
Discord Js playRawStream Error: spawn help ENOENT

### ISSUE THREAD

**Issue by Milodupipo** [hydrabolt/discord.js#571] opened 2016-08-30 17:43 UTC
I try to use the playRawStream function but it doesn't working. I found this code on another post around here. Could you explain me what is wrong here ?

```
        var chaine = msg.content.split(" ");
    	bot.joinVoiceChannel(bot.channels.get("name", "Général").id).then(function(r){
    	}).catch(function(error){
    		console.log(error);
    	});

    	if (bot.internal.voiceConnection) {
			var connection = bot.internal.voiceConnection;
			var request = require("request");
			var url = chaine[1];
			var stream = request(url);
			connection.playRawStream(stream).then(intent => {
				bot.reply(m, "playing!").then((msg) => {
					intent.on("end", () => {
						bot.updateMessage(msg, "that song has finished now.");
					});
				}).catch(error);
			}).catch(error); //error is a function who show errors on the console
		}
```

**Comment by GexoXYZ** [comment] 2016-08-30 18:11
Basically, you need to install ffmpeg and add it to the path.
Duplicate of #500 #429 #418 #286 #205

**Comment by Milodupipo** [comment] 2016-08-30 19:03
I already saw other posts and I installed ffmpeg, still doesn't work.

(For guys who need to install it on Ubuntu : https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu )

**Comment by GexoXYZ** [comment] 2016-08-30 19:15
Or do you get another error now?
(Or does it just not work)

**Comment by Milodupipo** [comment] 2016-08-30 19:20
Okay thanks, it wasn't in the PATH. However the error is still here, always on "playRawStream"
I just follow instructions here : http://discordjs.readthedocs.io/en/indev/troubleshooting.html
But nothing works

**Comment by GexoXYZ** [comment] 2016-08-30 19:25
Try clearing the npm cache and reinstalling discord.js, do you get any errors?
Also how does the output of `ffmpeg` look like?

**Comment by Milodupipo** [comment] 2016-08-30 19:38
Okay no more errors, but program does nothing.  Maybe the if block should be in the joinVoiceChannel block no ?

**Comment by appellation** [comment] 2016-08-30 20:43
I haven't tested this at all, but consider doing something along these lines.  https://gist.github.com/appellation/6ad6ba2446be7e2d76873ecfc43a6a1f

**Comment by Milodupipo** [comment] 2016-08-30 20:51
Thanks for the code but it's the same, no errors and no sound.

**Comment by appellation** [comment] 2016-08-30 21:10
Oh, if you're looking for a YouTube audio stream, check out this package.  https://www.npmjs.com/package/youtube-audio-stream

**Comment by Milodupipo** [comment] 2016-08-30 21:25
Okay it's working nice with youtube-audio-stream package. Thanks a lot for help :-)

**Closed** 2016-09-03 08:58 UTC
